name: what
author: min.huang@alumni.usc.edu
description: |
  What is GitHub Actions all about?

  https://docs.github.com/en/actions/learn-github-actions/contexts
inputs:
  output-directory:
    required: false
    default: ${{ github.workspace }}/output
runs:
  using: composite
  steps:
    - name: Make output directory
      shell: bash
      run: mkdir ${{ inputs.output-directory }}

    - name: Show env context
      shell: bash
      run: |
        value="${{ toJSON(env) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/env-context.txt

    - name: Show github context
      shell: bash
      run: |
        value="${{ toJSON(github) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/github-context.txt

    - name: Show inputs context
      shell: bash
      run: |
        value="${{ toJSON(inputs) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/inputs-context.txt

    - name: Show job context
      shell: bash
      run: |
        value="${{ toJSON(job) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/job-context.txt

    - name: Show matrix context
      shell: bash
      run: |
        value="${{ toJSON(matrix) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/matrix-context.txt

    - name: Print runner context
      shell: bash
      run: |
        value="${{ toJSON(runner) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/matrix-context.txt

    - name: Print steps context
      shell: bash
        value="${{ toJSON(steps) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/steps-context.txt

    - name: Print strategy context
      shell: bash
      shell: bash
        value="${{ toJSON(strategy) }}"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/strategy-context.txt

    - name: Print environment variables
      shell: bash
      run: |
        value="$(env)"
        echo "${value}"
        echo "${value}" > ${{ inputs.output-directory }}/env.txt

    - name: Upload data
      uses: actions/upload-artifact@v2
      with:
        path: output
