name: what
author: min.huang@alumni.usc.edu
description: What is GitHub Actions all about?
inputs:
  output-directory:
    required: false
    default: ${{ github.workspace }}/output
runs:
  using: composite
  steps:
    - name: Make output directory
      shell: bash
      run: mkdir ${{ inputs.output-directory }}

    - name: Print environment variables
      shell: bash
      run: |
        value = $(printenv)
        echo $value > ${{ inputs.output-directory }}/env.txt

    - name: Print env context
      shell: bash
      run: |
        value = '${{ toJSON(env) }}'
        echo $value > ${{ inputs.output-directory }}/env-context.txt

    - name: Print github context
      shell: bash
      run: echo '${{ toJSON(github) }}' > ${{ inputs.output-directory }}/env-context.txt

    - name: Print inputs context
      shell: bash
      run: echo '${{ toJSON(inputs) }}' > ${{ inputs.output-directory }}/inputs-context.txt

    - name: Print job context
      shell: bash
      run: echo '${{ toJSON(job) }}' > ${{ inputs.output-directory }}/job-context.txt

    - name: Print matrix context
      shell: bash
      run: echo '${{ toJSON(matrix) }}' > ${{ inputs.output-directory }}/matrix-context.txt

    #- name: Print needs context
    #  shell: bash
    #  run: echo '${{ toJSON(needs) }}' > ${{ inputs.output-directory }}/needs-context.txt

    - name: Print runner context
      shell: bash
      run: echo '${{ toJSON(runner) }}' > ${{ inputs.output-directory }}/runner-context.txt

    - name: Print step context
      shell: bash
      run: echo '${{ toJSON(step) }}' > ${{ inputs.output-directory }}/step-context.txt

    - name: Print strategy context
      shell: bash
      run: echo '${{ toJSON(strategy) }}' > ${{ inputs.output-directory }}/strategy-context.txt

    - name: Upload data
      uses: actions/upload-artifact@v2
      with:
        path: output
