name: What is GitHub Actions?

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  show:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Say what's up?
        uses: ./.github/actions/up-action
